name: Next Continuous Integration

on:
  push:
    branches: [master]

jobs:
  build_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
      - run: npm run build
